spring:
  application:
    name: entity-framework
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5050/db}
    password: ${DB_PASSWORD:pass}
    username: ${DB_USERNAME:user}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-outbox-master.xml
    enabled: true
